# Generated by Django 4.2.15 on 2024-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
